#!/usr/bin/env bash
# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: 2026 Richard de Vries · Jeffrey Everling · Malin Martinsen-Janssen · Suzanne Maquelin
# setup_sudoers.sh — Grant passwordless sudo for FanGetFameFast non-interactive commands.
#
# FanGetFameFast runs suricata-update at the start of every PCAP investigation
# without a TTY, so sudo cannot prompt for a password. This script writes a
# validated sudoers drop-in that grants the current user NOPASSWD access to
# the exact binaries that need it — no broader privileges are granted.
#
# Run once after initial installation:
#   bash scripts/setup_sudoers.sh
#
# Or called automatically by install_dependencies.sh.

set -euo pipefail

SUDOERS_FILE="/etc/sudoers.d/fangetfamefast"
CURRENT_USER="${SUDO_USER:-$(whoami)}"

C_CYAN='\033[0;36m'; C_GREEN='\033[0;32m'; C_YELLOW='\033[1;33m'
C_RED='\033[0;31m'; C_RESET='\033[0m'
info() { echo -e "${C_CYAN}[*]${C_RESET} $*"; }
ok()   { echo -e "${C_GREEN}[+]${C_RESET} $*"; }
warn() { echo -e "${C_YELLOW}[!]${C_RESET} $*"; }
err()  { echo -e "${C_RED}[✗]${C_RESET} $*" >&2; }

# ── Resolve binary paths ──────────────────────────────────────────────────────
SURICATA_UPDATE_BIN="$(command -v suricata-update 2>/dev/null || true)"

if [[ -z "$SURICATA_UPDATE_BIN" ]]; then
    warn "suricata-update not found — skipping sudoers entry for it."
    warn "Install Suricata first, then re-run this script."
    exit 0
fi

# ── Require root ──────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    info "Re-running with sudo …"
    exec sudo bash "$0" "$@"
fi

info "Configuring sudoers for user: $CURRENT_USER"
info "suricata-update path: $SURICATA_UPDATE_BIN"

# ── Build sudoers content ─────────────────────────────────────────────────────
SUDOERS_CONTENT="# FanGetFameFast — passwordless sudo for non-interactive forensic commands.
# Generated by scripts/setup_sudoers.sh. Do not edit manually.
# Required for: automated Suricata rule updates during PCAP investigation startup.
${CURRENT_USER} ALL=(ALL) NOPASSWD: ${SURICATA_UPDATE_BIN}
"

# ── Write to temp file and validate with visudo -c ───────────────────────────
TMPFILE="$(mktemp /tmp/fangetfamefast-sudoers-XXXXXX)"
trap 'rm -f "$TMPFILE"' EXIT

echo "$SUDOERS_CONTENT" > "$TMPFILE"

info "Validating sudoers syntax …"
if visudo -c -f "$TMPFILE" &>/dev/null; then
    ok "Syntax valid."
else
    err "Sudoers syntax check failed. Aborting — no changes made."
    visudo -c -f "$TMPFILE"   # print the error
    exit 1
fi

# ── Install ───────────────────────────────────────────────────────────────────
cp "$TMPFILE" "$SUDOERS_FILE"
chmod 0440 "$SUDOERS_FILE"
chown root:root "$SUDOERS_FILE"

ok "Installed: $SUDOERS_FILE"
echo ""
echo "  Grants $CURRENT_USER NOPASSWD: $SURICATA_UPDATE_BIN"
echo ""
ok "suricata-update can now run without a password or TTY."
